### ISSUE TITLE
Wrong count fields in method get_struc_kind( )

### ISSUE THREAD

**Issue by PShumilov** [ABAP-Logger/ABAP-Logger#100]
Hi!
Structures **BAPIRET1** and **BAPIRET2** have a field with name **MESSAGE**.
The CS operator will give the count 8. not 7:
```
        IF 'TYPE,NUMBER,ID,MESSAGE_V1,MESSAGE_V2,MESSAGE_V3,MESSAGE_V4,' CS |{ component-name },|.
          bapi_count = bapi_count + 1.
        ENDIF.
```

**Comment by PShumilov** [comment]
I am using the old system. There is no way to use new stuff – new options for Strings.
@vidyadharg, thanks for the explanation

**Comment by AlexandreHT** [comment]
Hi, I'm reopening the issue just to be sure I've understood the point. 
@PShumilov, do you have an issue because your system relies on an ABAP version earlier to 7.02 or do you have a test case that fails?

**Comment by PShumilov** [comment]
Hi, @AlexandreHT, my system relies on an ABAP version earlier to 7.02. I thought it wouldn't work because I got used to old syntax. After the explanation i understood that it would be work

**Comment by AlexandreHT** [comment]
Understook, thanks.
