### ISSUE TITLE
Dump MESSAGE_TYPE_UNKNOWN

### ISSUE THREAD

**Issue by christianguenter2** [ABAP-Logger/ABAP-Logger#106]
This code throws a short dump
`
zcl_logger=>new(
  )->add( |Test|
  )->export_to_table( ).
`

![grafik](https://user-images.githubusercontent.com/17437789/148352774-ed63711a-fdbe-445d-9ee9-5627c3477346.png)
![grafik](https://user-images.githubusercontent.com/17437789/148352936-95eac7bb-2557-4a9c-bbfc-d82e4ac2b6eb.png)

**Comment by chrisaasan** [comment]
Shouldnt line 19, "IF sy-subrc is initial.", rather be "IF sy-subrc not initial" ?

**Comment by christianguenter2** [comment]
No, I don't think so. This works if `TYPE` is supplied while adding log entries.
