### ISSUE TITLE
display context

### ISSUE THREAD

**Issue by nikolasmylonas** [ABAP-Logger/ABAP-Logger#108]
be able to attached extra fields on error line save to database and be able to view the fields on the display by custom transaction in alv like now but to be searchable. 

something like below
![image](https://user-images.githubusercontent.com/66404940/163688230-6616660d-f257-4093-b8f1-9d0e411b3eec.png)

find a resource https://oprsteny.cz/?p=249
also [vidyadharg](https://github.com/vidyadharg) upload a version that says is working but the new method are missing from github.
https://github.com/ABAP-Logger/ABAP-Logger/issues/71

**Comment by vidyadharg** [comment]
Hi [nikolasmylonas](https://github.com/nikolasmylonas) ,

I am working on keep my version up to date with the option to add custom fields in context. I will keep you posted.

**Comment by AlexandreHT** [comment]
Hi, please do not hesitate to create a PR.

**Comment by vidyadharg** [comment]
Enhancement already completed via PR [class for display profile #119  ](https://github.com/ABAP-Logger/ABAP-Logger/pull/119). so this should be good to close.

**Comment by mbtools** [comment]
closed by #119
