### ISSUE TITLE
Redundant to SAP-Standard

### ISSUE THREAD

**Issue by ThomasErgin** [ABAP-Logger/ABAP-Logger#112]
Thanks for providing your solution in Github. 

However, I found the solution to be somewhat redundant to the SAP-Standard. You don't have to use the BAL_LOG-BAPIs. SAP provides a big number of logger classes, that can be used in a similar way, e.g. the class cl_bal_logger:

```
TRY.
    cl_bal_logger=>initialize( EXPORTING i_log_object = NEW cl_bal_logobj( i_log_object = 'FOO'  ) ).
    cl_bal_logger=>add_errortext( i_errortext = 'An error occurred' ).
    cl_bal_logger=>add_statustext( i_statustext = 'A nice status message' ).
    cl_bal_logger=>add_msg( i_probclass = if_sbal_logger_config=>c_probclass_none ).
    cl_bal_logger=>save_to_db( ).
  CATCH cx_bal_exception INTO DATA(log_exception).
ENDTRY.
```
This might be an alternative for those, who do not want to download 3rd-Party-Solutions to their SAP-System.

Happy Coding!

**Comment by AlexandreHT** [comment]
Hi, 
All the credit for the initial work should go to @epeterson320! 
To my opinion, the main value added of ABAP-Logger compared to standard function module/classe is its ability to handle any kind of message without fuss (eg bapiret2). 
But it's true, some of us still have to work in an environment where ABAP open source libraries are not available...

**Comment by andkopp** [comment]
Hi @ThomasErgin. 
Thank you for this hint. Do you know the ABAP platform release this class was introduced to SAP standard?
Best regards, Andreas

**Comment by ThomasErgin** [comment]
Hi @andkopp,
The mentioned class CL_BAL_LOGGER has been created 18.08.2015 and can be found in newer SAP releases, such as SAP_BASIS	756	SP 0001.
However, there are dozends of logger classes in SAP, that work similar, e.g.
CL_HP_LOGGER
CL_SBAL_LOGGER
CL_CRM_SOC_LOGGER
...
You might want to check out one of those or search for others. 

Hard for me to understand, why SAP AG did not provided a central, more generic solution for that. 
Cheers
Thomas
