### ISSUE TITLE
Test classes use APPEND xxx TO yyy on sorted tables 

### ISSUE THREAD

**Issue by cavabap** [ABAP-Logger/ABAP-Logger#113]
Hallo,
bal_t_logn and bal_t_logh are sorted tables.
The UTs should be inserting into the tables rather than appending. In general this could lead to a dump (but who cares, its a UT and this won't happen).

But a needless postivie ATC positive finding is distracting.

Check Title: Search for APPEND and INSERT ... INDEX in SORTED Tables   
Check Message: APPEND to SORTED Table ...   
Priority: Priority 2   
APPEND to SORTED Table LT_LOG_HANDLES 
The message can be suppressed with pseudo comment "#EC #EC CI_APPEND_OK 

Is there a reason to use APPEND rather than INSERT?

If not, I'd be happy to submit a PR with a fix.

Thanks

Martin

**Comment by AlexandreHT** [comment]
Hi, 
I don't see any particular reason. We'll be happy with a PR.
Thanks,

**Comment by cavabap** [comment]
Hi, no problem, my pleasure.

A little detail i just noticed on my customer system (7.50). The pragma ##NO_TEXT doesn't exist on 7.50- its newer HANA?). The correct psedo comment for an older ABAP system would be "#EC NOTEXT. Should I submit a new PR to change ##NO_TEXT into "#EC NOTEXT? On older ABAP systems this shows up as PRAGMA NO_TEXT is unknown.

Thanks

Martin

**Comment by AlexandreHT** [comment]
Yes please, so it'll be clean on every release.
