### ISSUE TITLE
callback routine useless

### ISSUE THREAD

**Issue by Ennowulff** [ABAP-Logger/ABAP-Logger#117]
Hey there! 
IMHO the call back routine provided at method ADD is not very useful.
When logging a message some useless parameters are returned.
in my case two entries: 
Parameter V1 contains the message
Parameter %LOGNUMBER contains value "$000001"

I think that also the values table should be supported BAL_S_PARM-T_PAR so that I am allowed to pass reasonable values to that specific message.

or did I get something wrong how to use the callback?

Thanks

**Comment by christianguenter2** [comment]
Hi Enno,

I use the callbacks too and in our scenario %LOGNUMBER is filled (as the log is persisted I think) and we use it to retrieve additional information and to some further actions upon that. 

Regarding your comment about BAL_S_PARM-T_PAR, I second that. And there's currently no way to supply them AFAIS. But that should be quite easy to implement though. Did a small prototype and it seems working. I'll try to prepare a PR soon.

BR Christian

**Comment by christianguenter2** [comment]
@Ennowulff can you test the pull request?

**Comment by andkopp** [comment]
Hi @christianguenter2 @Ennowulff
What is the purpose of the callback parameter? Are these parameters also visible in transaction SLGD?
BR Andreas

**Comment by Ennowulff** [comment]
You can provide additional/ technical information that can be used when clicking „message detail“.
Am 23. Sept. 2022, 16:49 +0200 schrieb Andreas Kopp ***@***.***>:

**Comment by christianguenter2** [comment]
Short example:
```
DATA(named_log) = zcl_logger=>new(
                      object = 'ABAPUNIT'
                      subobject = 'LOGGER'
                      auto_save = abap_true ).

named_log->s(
    obj_to_log          = |Document created|
    callback_fm         = 'ZDT_LOGGER_CALLBACK'
    callback_parameters = VALUE #( ( parname = 'DOCNO' parvalue = '12345678' ) ) ).

```
![grafik](https://user-images.githubusercontent.com/17437789/192083235-8f2c80bb-5d6c-49bd-953e-12cd2b7265fb.png)
![grafik](https://user-images.githubusercontent.com/17437789/192083248-bbcfbdb0-7d33-4331-8d9b-30e1e1c105e3.png)
![grafik](https://user-images.githubusercontent.com/17437789/192083265-654ce9fc-c7f4-4328-9648-420aceddf9a0.png)

AFAIK there's no way of inspecting the parameters in SLGD. If there is one I'd be eager to know :-)
