### ISSUE TITLE
Importance is not propagated when logging a table

### ISSUE THREAD

**Issue by jrgkraus** [ABAP-Logger/ABAP-Logger#121]
When logging a table, ADD( ) loops the lines of the table and calls itself. However, the IMPORTANCE parameter is not passed to the line call.

**Comment by jelliottp** [comment]
We are working to implement this for the first time, and this is one of the first things we just ran into as well. Problem class then appears as "Other" in SLG1.

Until now, we assigned problem classes based on the message types, e.g.: `a` & `e` -> Very Important

I'd also be curious if others do something similar, and if there would be a way to handle this with ABAP logger.

**Comment by AlexandreHT** [comment]
I use the "Other" message type (<=> empty) for logging user entries on wireless devices. It serves as a severity 7 in the [RFC 5424](https://www.rfc-editor.org/rfc/rfc5424) standard.

**Comment by jelliottp** [comment]
Went ahead and proposed this change: https://github.com/ABAP-Logger/ABAP-Logger/pull/124

**Comment by AlexandreHT** [comment]
Merged, thanks
