### ISSUE TITLE
Unit tests use non-existing SLG0 subobject

### ISSUE THREAD

**Issue by jrgkraus** [ABAP-Logger/ABAP-Logger#122]
I was not able to run the unit tests in my system because the sub object ABAPUNIT/LOGGER does not exist in my system. 
I didn't want to create this sub object with SLG0 because it is not in the customer name space.
As a workaround, I used ABAPUNIT/<space> - everything worked fine then.

**Comment by HuprichT** [comment]
Hi,

was able to reproduce the Issue in ABAP Systems with NW 7.50 and 7.56, there is no subobject 'LOGGER' for existing Object 'ABAPUNIT'.

Could you show the Code how you have fixed this?
For me it was working when I cleared the subobject. Without it, a Log is nevertheless set

**Comment by AlexandreHT** [comment]
Hi, 
@HuprichT : Subobject LOGGER is not a standard one. cf. https://github.com/ABAP-Logger/ABAP-Logger#run-unit-tests

@jrgkraus : I shall say I didn't try without subobject. Do result show up in SLGD for ABAPUNIT ? (expected result below:
![image](https://user-images.githubusercontent.com/44161780/218074777-c5ec43ab-5a17-4d87-986c-5a58677ac82f.png) If so, would you consider creating a PR?

**Comment by jrgkraus** [comment]
Our systems are down because of a cyber attack :-( As soon as possible, I will post the coding

**Comment by jelliottp** [comment]
> Can confirm that Logs are created and saved without providing any subobject. Will wait for answer of @jrgkraus regarding PR, else I am going to create one.

Can also confirm this, since I ran into this same issue. Any update here?

Personally I feel it would be better for users to not have to maintain any sub-object. Alternatively ZLOGGER sub-object would be preferable.
