### ISSUE TITLE
Limited Test Double Framework compatibility?

### ISSUE THREAD

**Issue by jelliottp** [ABAP-Logger/ABAP-Logger#123]
Unless I'm missing something, it seems like the logger has limited compatibility with the ABAP Test Double Framework. This is because log creation requires a static method and I don't want logs to be created when tests are executed.

I can call `zcl_logger_factory=>create_log( )` in the constructor of my calling class, and then inject a test double for the unit tests. This works.

However, it appears as if this limits us to only be able to create one log per instance of the calling class. Is this intended? It may be helpful to have an instance method for `create_log( )` to allow for this.

Or is there another way to implement this, so that I could create multiple logs (typically with different external IDs) and still maintain unit testability?

**Comment by chrisaasan** [comment]
If I remember correctly I had a similar issue once, I think I got around it by createing the log with setting auto_save = abap_false in my test.

**Comment by AlexandreHT** [comment]
I usually don't use more than one logger by class so I never looked further. You could inject a repository class (as repository in DDD) that handles all the loggers and inject a test double of the logger repository class into your class under test.

Another path would be the dependancy lookup showcased in the [Writing Testable Code on openSAP](https://open.sap.com/courses/wtc1/items/1dSsuE10JXd0GU4GqiTQId) (see also https://blogs.sap.com/2018/04/14/sap-open-course-unit-testing-week-5-dependency-lookup/)
