### ISSUE TITLE
BAL-Log-Handle remains after destruction of ABAP-Logger

### ISSUE THREAD

**Issue by Wacda** [ABAP-Logger/ABAP-Logger#130]
The internal logic of the FM "BAL_LOG_CREATE" create entries in the global table \<G\>-T_LDAT.
After freeing the ABAP-Logger-Object the generated entries remains in the table \<G\>-T_LDAT.

I suggest the following solution idea:

Two FM clean the table \<G\>-T_LDAT: "BAL_LOG_DELETE" or "BAL_LOG_REFRESH". 
"BAL_LOG_DELETE" is not usable because it deletes the message entries from the memory and the db.
"BAL_LOG_REFRESH" can be used because it deletes the message entries only from the memory but not from the db.
 
So I suggest to add a method FREE which uses the FM "BAL_LOG_REFRESH". 
To get more safety to save messages from the memory into the db the method save() should be called before the FM call.

**Comment by mbtools** [comment]
Create a pull request 😄
