### ISSUE TITLE
Build Hierarchy with Logger

### ISSUE THREAD

**Issue by HuprichT** [ABAP-Logger/ABAP-Logger#140]
Currently it is not possible to build a Hierarchy with the Logger. 
Thats unfortunate, especially if you have Large Procedures where you want to group the results.

To implement this a new Importing Parameter is applied and minor adjustments within the add( ) Method. 

Call would look like this for example:
```
"First Group
 log->s( obj_to_log = 'Airline 1' detlevel = '1' ).
 log->e( obj_to_log = 'Passenger 123736GHB has not arrived at the Gate' detlevel = '2' ).
```
![image](https://github.com/ABAP-Logger/ABAP-Logger/assets/45813255/828884e2-641f-4c7c-afcf-3824203f5f1b)

What do you think? 

**I have made the adjustments and its working with all named Messaging Types. Will provide Pull Request with Code when I'm at home**

**Comment by mbtools** [comment]
I like it. Please create a PR. Just remember to make all new parameters optional.

**Comment by HuprichT** [comment]
#148
