### ISSUE TITLE
Navigation to the application Log is not working for background jobs

### ISSUE THREAD

**Issue by hannemac** [ABAP-Logger/ABAP-Logger#143]
To connect the application log with a background job, the function module **BP_ADD_APPL_LOG_HANDLE** should be executed with the log-handle as a parameter, when the log is saved in background mode (sy-batch = abap_true).

```
IF sy-batch = abap_true.

    CALL FUNCTION 'BP_ADD_APPL_LOG_HANDLE'
        EXPORTING
            loghandle = me->handle
        EXCEPTIONS
            OTHERS    = 0.

ENDIF.
```

Then the navigation via SM37 and menu Goto / Application Log is working.

![image](https://github.com/ABAP-Logger/ABAP-Logger/assets/6243420/edb74447-ccb9-4574-8f0b-7df621b92ddd)

**Comment by mbtools** [comment]
Closed by #146
