### ISSUE TITLE
Stale project?

### ISSUE THREAD

**Issue by mbtools** [ABAP-Logger/ABAP-Logger#147]
It appears that the project is stale. It would be a shame to not keep it going. 

I'm happy to become a more active maintainer (vet and merge PRs). Interested?

Best,
Marc

**Comment by andkopp** [comment]
I have to admit that I have not been very active in the last years. Help is always welcome. What do you think @AlexandreHT?

**Comment by AlexandreHT** [comment]
I'd say I'm actively maintaining from time to time. Anyway, considering all the activity Marc has put into the project (PR, reviews and comments), it's a no-brainer. 
Marc, I've added you to the maintainers' group. Welcome!

**Comment by mbtools** [comment]
Great! Let's have a short chat next week. are you on the [abapgit slack](https://communityinviter.com/apps/abapgit/abap), @AlexandreHT?

**Comment by jelliottp** [comment]
Great to have you added @mbtools, I agree this is a valuable tool and I also wouldn't want to see it lose support.
