### ISSUE TITLE
Add support for BAPI_ALM_RETURN message structure

### ISSUE THREAD

**Issue by Xylaw** [ABAP-Logger/ABAP-Logger#154]
BAPI _BAPI_ALM_CONF_CREATE_ returns messages of type **BAPI_ALM_RETURN**. This type is not supported by the loggers message structure determination:

```
  zcl_logger_factory=>create_log( )->add(
    VALUE bapi_alm_return(
      type           = 'W'
      message_id     = 'BL'
      message_number = '001'
      message_v1     = 'This'
      message_v2     = 'is'
      message_v3     = 'a'
      message_v4     = 'test' ) )->display_fullscreen( ).
```
![bapi_alm_return](https://github.com/ABAP-Logger/ABAP-Logger/assets/31725458/c599bec9-3db7-484d-9aac-7c90d1c79923)

If it's ok, I will provide pull request with necessary code enhancements (incl. unit tests) to support **BAPI_ALM_RETURN**.

What do you think?

**Comment by AlexandreHT** [comment]
With pleasure. Could you please have a look to issue #60 and PR #77 to ensure your code is compatible with systems that don't have this structure (eg. Solman). Thanks
