### ISSUE TITLE
System message is logged if initial object is passed to as object to log

### ISSUE THREAD

**Issue by kjetil-kilhavn** [ABAP-Logger/ABAP-Logger#168]
If an initial object, e.g. an empty return messages table, is passed to the logger, the logger logs the system message. That is very often not the desired behaviour.

Imagine the following lines of code
```
CALL FUNCTION 'SAP_STANDARD_FUNCTION'
  IMPORTING messages = DATA(return_messages)
log->add( return_messages ).
IF NOT log->is_empty( ).
  log->save( ).
ENDIF.
```

If SAP_STANDARD_FUNCTION returns an empty MESSAGES table the expected behaviour is that the log isn't saved.

The actual behaviour is that "random" message is logged, and the log is saved.

There are quite a few SAP standard function modules which returns an empty message table instead of a table with a single success message when everything goes well. 

In method zif_logger~add the following lines
```
    IF obj_to_log IS INITIAL.
      detailed_msg = add_syst_msg( syst_buffer ).
```
should be changed to
```
    IF obj_to_log IS NOT SUPPLIED.
      detailed_msg = add_syst_msg( syst_buffer ).

```

I hope to submit a pull request soon unless someone beats me to it.

**Comment by kjetil-kilhavn** [comment]
I checked in one of our other system lines, and this is a regression that was introduced in https://github.com/ABAP-Logger/ABAP-Logger/commit/937010a0d3b4f3dc23dfc99c185859ab57f570b7

**Comment by Kaszub09** [comment]
The only option I see is to applies change with `IS NOT SUPPLIED` and then in all of those i,a,e,w,s methods change code to something like:
```
    IF obj_to_log IS SUPPLIED.
      self = add(
          obj_to_log          = obj_to_log
          context             = context
          callback_form       = callback_form
          callback_prog       = callback_prog
          callback_fm         = callback_fm
          callback_parameters = callback_parameters
          type                = 'A'
          importance          = importance
          detlevel            = detlevel ).
    ELSE.
      self = add(
          context             = context
          callback_form       = callback_form
          callback_prog       = callback_prog
          callback_fm         = callback_fm
          callback_parameters = callback_parameters
          type                = 'A'
          importance          = importance
          detlevel            = detlevel ).
    ENDIF.
```
Or maybe even abstract it to another method which takes `is_supplied` parameter of `abap_bool`, set explicitly by i,a,e,w,s.
Although that's a lot of boilerplate code. Unless there are other ideas?

**Comment by kjetil-kilhavn** [comment]
I have had little time to think about it since I first created this issue, but that is one of the two solutions me and the developer who reported it to me have come up with. The other idea we have is to move the is initial check to the end, but that must be investigated a bit. When things quiet down at work (hah!) I will add a unit test for our failing test case and try it out.
