### ISSUE TITLE
Error Adding Structure/Internal Table to Context

### ISSUE THREAD

**Issue by Entharia** [ABAP-Logger/ABAP-Logger#175]
Hello, I've been encountering an error when attempting to add a structure or internal table to the context.

```abap
log->e( obj_to_log = 'Erstellen der Nachricht fehlgeschlagen', context = ls_nast ).
log->e( obj_to_log = 'Erstellen der Nachricht fehlgeschlagen', context = lt_nast ).
```

The context type is `any`, which led me to believe this approach should work, but surprisingly, it doesn't.

The error occurs at `formatted_context-value`, where it fails because `value` is defined as `char256`, and the code attempts to assign a structure or internal table to it.

Before I modify the code, could you advise if there’s a correct way to include a structure/internal table in the context?

Thank you!

**Comment by mbtools** [comment]
Context data is hardcoded by SAP to char256. Structures or tables won't work. 

![image](https://github.com/user-attachments/assets/3df04935-b36c-4951-894c-73a8479bd6bb)

Either you create multiple messages (for the fields of the structure), or try using `callback_parameters`.
