### ISSUE TITLE
Method to get last used logger?

### ISSUE THREAD

**Issue by andkopp** [ABAP-Logger/ABAP-Logger#18]
Let's start a discussion. I am looking for a solution to get the _last used logger object_. Normally I initialize the logger class in the constructor of a using class, assign it to a private instance attribute and use it in the methods of the using class.

Sometimes you want to use the same logging object in static methods of the class or in other classes in the context of the same program. I think it is not a good idea to pass the reference to the logger by a parameter. 

As ABAP does not offer dependency injection I would suggest to add some kind of static method like "get_last". When an instance of ZCL_LOGGER is created we could save this reference in a static attribute of ZCL_LOGGER, and return it if "get_last" is called. What do you think about this?

**Comment by apex8** [comment]
Maybe this is nothing that should be added to the "core" implementation.
For a singleton like implementation and a logger group implementation I
created a wrapper classes that provides this features. By using this
approach I was able to keep the "abap-logger" clean and I`m able to pull
some newer version if any would become available.

Is this an option to you?

**Comment by andikade** [comment]
Yes, this is an option. This reminds me of the principle of "separation of concerns". 

Should we extract the management of the instances (creation, get, etc.) completely into another factory like class?

**Comment by andikade** [comment]
On the one hand, I just thought it would be easier to put this in the same class. On the other hand, we could add an interface (for the public methods add, a, e, w, i, s...) and a factory class which manages objects of ZCL_LOGGER.

**Comment by AlexandreHT** [comment]
I'm closing this issue because it's old and I don't think either it should be included in the library.
