### ISSUE TITLE
Support for logging any deep structure/table

### ISSUE THREAD

**Issue by andkopp** [ABAP-Logger/ABAP-Logger#21]
I'd like to be able to log any deep structure or table (...and not only BAPIRET2, BDCMSGCOLL and HRPAD_MESSAGE). 
My use case is to log the request and response structure of a SOAP web service call (which often consists of table types) if it fails.
I could imagine converting structures and tables to a JSON like string, pretty print it (with line breaks) and logging it line by line.
What do you think?

**Comment by kjetil-kilhavn** [comment]
This issue could be closed now, could it not?

**Comment by kjetil-kilhavn** [comment]
I noticed only one problem with the new support for any structure, and that is that fields in .INCLUDE structures are not logged unless the .INCLUDE has been named ('Group')

**Comment by andkopp** [comment]
Thanks for testing. I will check on that. If you already know how to fix it, you can create a pull request.
Support for tables is still missing. That is the main reason this issue is still open.

**Comment by kjetil-kilhavn** [comment]
For the moment I updated the structures i needed to log and named the includes, as they were in customer name space. I'll have a look at it and let you know (e.g. with pull request) if I find a solution.

**Comment by kjetil-kilhavn** [comment]
The solution to log all INCLUDE structures is quite simple.
Use sy-tabix instead of component name, so in the add_structure method:. 
    loop at components into component.
      assign component sy-tabix of structure obj_to_log to <component>.
Looking into logging of tables.
