### ISSUE TITLE
BAL_LOG_MSG_ADD_FREE_TEXT and formatted_context

### ISSUE THREAD

**Issue by schealex** [ABAP-Logger/ABAP-Logger#55]
Hello guys,

i've encountered a weired issue where if you want to log a free text and supply a context the BAL function returns an exception (which are not cought at all in the logger btw) reporting inconsistency in the context. This is because the type description will return the base structure but not the one you supplied [zcl_logger.clas.abap#L271.](https://github.com/epeterson320/ABAP-Logger/blob/master/zcl_logger.clas.abap#L271).

If I supply the context directly it works flawless without any problems. Is there a reason for supplying the formatted_context in [zcl_logger.clas.abap#L407](https://github.com/epeterson320/ABAP-Logger/blob/master/zcl_logger.clas.abap#L407)?

Regards
Alex

**Comment by anuragguptagithub** [comment]
I had the same situation but then I realized via the code that I was passing it the wrong way.
You just have to pass a work area and the code inside figures out the corresponding table ( global structure name ) and populates the context-tabname and value on its own.

**Comment by AlexandreHT** [comment]
I suppose your question has been answered. Please do not hesitate to reopen is issue if need be.
