### ISSUE TITLE
Interface methods in wrong namespace

### ISSUE THREAD

**Issue by pvaczi** [ABAP-Logger/ABAP-Logger#59]
I installed ABAP-Logger yesterday.
If I try to double click the method ZIF_LOGGER~ADD (or any other implemented interface method) nothing happens. I looked the code in source view and I see this:

* <SIGNATURE>---------------------------------------------------------------------------------------+
* | Instance Private Method ZCL_LOGGER->ADD
* +-------------------------------------------------------------------------------------------------+
* +--------------------------------------------------------------------------------------</SIGNATURE>
  method add.

    data: detailed_msg         type bal_s_msg,
          exception_data_table type tty_exception_data,
          free_text_msg        type char200,
          ctx_type             type ref to cl_abap_typedescr,
...

I think it should be:

method ZIF_LOGGER~ADD.

Can it happen because an AbapGit version change? I use AbapGit 1.97.0.

Btw, somehow it works anyway :)

**Comment by andkopp** [comment]
Yes, it is weird, but it works. As far as I know this navigation problem exists only in SE80 but not in Eclipse.

When I refactored the code and added the factory and interface, one goal was to get backwards compatibility so I did not change the names of the methods but instead added alias names for the interface:

`aliases:  add for zif_logger~add`

So despite the refactoring you can still call the methods directly without using the factory and the interface (but you should not). 
If you change add to zif_logger~add, direct calls probably won't work anymore unless there is a way to change the alias accordingly as well.

**Comment by AlexandreHT** [comment]
I renamed the methods and checked for regression. It's ok. 
Direct calls to zcl_logger->add( ) reach zcl_logger->zif_logger~add( ) via the alias.
