### ISSUE TITLE
Syntax error in NW 752 dev edition - bapi_order_return is unknown

### ISSUE THREAD

**Issue by christianguenter2** [ABAP-Logger/ABAP-Logger#60]
Structure bapi_order_return doesn't exist on bare netweaver systems
![image](https://user-images.githubusercontent.com/17437789/86366219-cf68b800-bc7a-11ea-8150-e1aea7e78fdc.png)

**Comment by andkopp** [comment]
You are right. It should be replaced.

**Comment by vikdb** [comment]
I have the same problem, how do i fix this?

**Comment by AlexandreHT** [comment]
My guess would be to drop depencies to actual dictionary structure and move entirely to dynamic programming with data references. 
I don't have time right now to work on a fix (probably in next month if you don't tackle the issue before).

**Comment by chrisaasan** [comment]
One posibility is to create a type in the class which matches the DDIC type, as is done for the hrpad_message.
``
* Local type for hrpad_message as it is not available in an ABAP Development System
    types: begin of hrpad_message_field_list_alike,
             scrrprfd type scrrprfd.
    types: end of hrpad_message_field_list_alike.

    types: begin of hrpad_message_alike,
             cause(32)    type c,                          "original: hrpad_message_cause
             detail_level type ballevel.
            include type symsg .
    types: field_list type standard table of hrpad_message_field_list_alike
           with non-unique key scrrprfd.
    types: end of hrpad_message_alike.
``

**Comment by PrieJos** [comment]
Hello,

It would be great to know whether you have any plan to pull the fix to this issue any time soon. 

Thanks
Jose M. Prieto

**Comment by pvaczi** [comment]
It could use field-symbols type any, and assign the components with with "assign component 'ID' of structure <bapi_order_msg> to <field_id>."
Of course in this case we don't need extra fs for all struc. Instead <bapi_order_msg> we can use <any_message>, and instead <field_id> <any_field>.
I use it this way in another code:
  DEFINE __cp_any_msg_fld.
    ASSIGN COMPONENT &2 OF STRUCTURE &1 TO <any_field>.
    &3 = <any_field>.
  END-OF-DEFINITION.
    __cp_any_msg_fld: is_trlomesg 'MSGID' gv_msgid,
                      is_trlomesg 'MSGTY' gv_msgty,
                      is_trlomesg 'MSGNO' gv_msgno,
                      is_trlomesg 'MSGV1' gv_msgv1,
                      is_trlomesg 'MSGV2' gv_msgv2,
                      is_trlomesg 'MSGV3' gv_msgv3,
                      is_trlomesg 'MSGV4' gv_msgv4.

It is slower though.
