### ISSUE TITLE
new method get() instead of new() and open() with rename of desc field

### ISSUE THREAD

**Issue by anuragguptagithub** [ABAP-Logger/ABAP-Logger#69]
Hi Guys

Comparing with other modern languages, I think we should not have two methods , one to create log with new and other to open it . One should think of a simple method like get() which returns the log object if it does not exists based on the desc ( external number ) field.
Also, desc field should not be meant for description but it is close to being like log handle. generally in Java or Python, the logger takes class name or prgram name to log all its messages, and thats how one would know in a log file about where the log comes.
The desc should by default have sy-repid as input but it could be different based of complex application like a transaction id throughout a transaction.

**Comment by AlexandreHT** [comment]
Hi, 
Some would say that a get method that doesn't not find an entry in the persistence layer should return an exception. I prefer to leave that choice to the code that calls that ABAP-Logger library.
