### ISSUE TITLE
Is it possible to load and show existing log with this ?

### ISSUE THREAD

**Issue by vikdb** [ABAP-Logger/ABAP-Logger#70]
Title

**Comment by vidyadharg** [comment]
Try this.

     data R_LOG type ref to ZCL_LOGGER.
     
      r_log ?= zcl_logger_factory=>open_log(
        object = object
        subobject = subobject
        desc = desc
        create_if_does_not_exist = create_if_does_not_exist
        settings = zcl_logger_factory=>create_settings(
          )->set_autosave( auto_save )
      ).

**Comment by AlexandreHT** [comment]
I suppose your question has been answered. Please do not hesitate to reopen is issue if need be.
