### ISSUE TITLE
may i ask how to use context?

### ISSUE THREAD

**Issue by zeafreeks** [ABAP-Logger/ABAP-Logger#71]
i need to know how to use something like this 
https://www.sapalles.com/2014/10/24/add-extra-custom-fields-to-application-log/

where I can insert a new column in between type and messages

**Comment by vidyadharg** [comment]
Check my fork https://github.com/vidyadharg/ABAP-Logger

I created method ZIF_LOGGER_SETTINGS~SET_DISPLAY_PROFILE  and ZIF_LOGGER_SETTINGS~GET_DISPLAY_PROFILE.

changes in ZCL_logger.

  METHOD zif_logger~fullscreen.

    DATA:
      profile        TYPE bal_s_prof,
      lt_log_handles TYPE bal_t_logh.

    APPEND me->handle TO lt_log_handles.

    profile = settings->get_display_profile( ).

    IF profile IS INITIAL.
      CALL FUNCTION 'BAL_DSP_PROFILE_SINGLE_LOG_GET'
        IMPORTING
          e_s_display_profile = profile.
    ENDIF.

    CALL FUNCTION 'BAL_DSP_LOG_DISPLAY'
      EXPORTING
        i_s_display_profile = profile
        i_t_log_handle      = lt_log_handles.

  ENDMETHOD.

changes in calling program

FORM create_display_profile.
  DATA:
    lv_expire           TYPE aldate_del,
    l_s_display_profile TYPE bal_s_prof,
    l_s_fcat            TYPE bal_s_fcat,
    ls_context          TYPE zstbal_closing_periods,
    lv_col_pos          TYPE i.

  CONSTANTS : lc_bal_context TYPE lvc_rtname VALUE 'ZSTCLOSEPERIODS'.

  DEFINE a_fcat.

    l_s_fcat-ref_field = &1.
    l_s_fcat-ref_table = &2.
    l_s_fcat-col_pos   = lv_col_pos = lv_col_pos + 1.
*    l_s_fcat-colddictxt = 'S'.

    APPEND l_s_fcat TO &3.
    CLEAR l_s_fcat.

  END-OF-DEFINITION.


* set title of dynpro
  l_s_display_profile-title     = sy-title.
* set header of tree
  l_s_display_profile-head_text = 'Pstng period variant List'.

************* define structure of level 1 in tree
* external number
  l_s_fcat-outputlen  = 40.
  a_fcat 'EXTNUMBER' 'BAL_S_SHOW' l_s_display_profile-lev1_fcat.
************* define structure of level 2 in tree
  l_s_fcat-coltext = 'Pstng period variant'.
  l_s_fcat-cltxt_add = 'X'.
  l_s_fcat-cltxt_len = 12.
*  l_s_fcat-is_extern = 'X'.
  l_s_fcat-outputlen  = 8.
  a_fcat 'TX_BUKRS' lc_bal_context l_s_display_profile-lev2_fcat.
  l_s_fcat-outputlen  = 4.
  a_fcat 'BUKRS' lc_bal_context l_s_display_profile-lev2_fcat.

  logger =  zcl_logger_factory=>create_log(
     EXPORTING
       object    = 'FICO'
       subobject = 'Z123'
       desc      = 'ALL List'
*    context   = ls_context
       settings  = zcl_logger_factory=>create_settings(
*            )->set_expiry_date( lv_expire
*            )->set_autosave( lv_autosave
             )->set_must_be_kept_until_expiry( abap_true
             )->set_display_profile( EXPORTING i_display_profile = l_s_display_profile context = ls_context
         )
       ).

ENDFORM.
sample output...
![image](https://user-images.githubusercontent.com/28149363/104301514-c0967400-54ed-11eb-8509-0c8274961306.png)

**Comment by AlexandreHT** [comment]
I suppose your question has been answered. Please do not hesitate to reopen is issue if need be.
