### ISSUE TITLE
Unit Tests don't all success in languages other than English (e.g. German)

### ISSUE THREAD

**Issue by martinandrewcavanagh** [ABAP-Logger/ABAP-Logger#78]
Its really not so important...but it think the tests should run in any language.

zcl_logger->lcl_test->can_log_batch_msgs() + zcl_logger->lcl_test->can_log_chained_exceptions

**Comment by AlexandreHT** [comment]
I don't have issues on my system in French, what's the actual result?
Have you tried changing the language to ```sy-langu``` in ```format_message```

**Comment by martinandrewcavanagh** [comment]
can_log_batch_msgs, 'Did not log BDC return messages correctly'
can_log_chained_exceptions: 'Did not log chained exception correctly'
The Details are, 
"Erwartet [Specify the object to be tested], tatsächlich [Geben Sie das zu testende Objekt an]"
which translates to,
"Expected [Specify the object to be tested], actual [Geben Sie das zu testende Objekt an]"

I'm actually logged in German. But when the unit tests are executing in Eclipse / SAP GUI, sy-langu = 'E'.
When zcl_logger->lcl_test->get_messages ->call function 'BAL_LOG_MSG_READ' is called, the SAP system returns the messages in German.

Even when I alter the call to 'BAL_LOG_MSG_READ' with the language parameter, the messages are still returned in German.

call function 'BAL_LOG_MSG_READ'
        exporting
          i_s_msg_handle = msg_handle
          i_langu = 'E'
        importing
          e_s_msg        = msg_detail
          e_txt_msg      = msg_text. "messages are still in German!

When I dived into the function module 'BAL_LOG_MSG_READ' and debugged it, I found the text was set in the Function Module 'BAL_DSP_TEXT_MSG_READ' with the following code.

* when language is current language, use MESSAGE INTO
  IF i_langu = sy-langu.
    MESSAGE ID     i_msgid
            TYPE   'S'
            NUMBER i_msgno
            WITH   i_msgv1
                   i_msgv2
                   i_msgv3
                   i_msgv4
            INTO   e_message_text.
    EXIT.
  ENDIF.

i_langu = 'E' and sy-langu = 'E' - but for some reason the text is being returned in German! This is very strange.
I assume this is somehow because my Eclipse / SAP GUI login language is German - but the Unit Tests are being executed in English and somehow this is messing the MESSAGE statement up.

format_message is returning the text in English (as it should).

This affects both SAP GUI and Eclipse.

Changing the FORMAT_MESSAGE language from 'E' to sy-langu didn't change anything. It always returned the messages in English...
I did manage to fix the problem by exchanging CALL FUNCTION 'FORMAT_MESSAGE' by using MESSAGE directly.
This way I get the same 'curious' language behaviour and the test (that the texts are the same) passes.

  method format_message.
*    call function 'FORMAT_MESSAGE'
*      exporting
*        id        = id
*        lang      = 'E'
*        no        = no
*        v1        = v1
*        v2        = v2
*        v3        = v3
*        v4        = v4
*      importing
*        msg       = msg
*      exceptions
*        not_found = 1
*        others    = 2.
**      TODO: raise abap unit
    MESSAGE ID id TYPE 'S' NUMBER no WITH v1 v2 v3 v4 INTO msg.
  endmethod.

Obviously my fix is dependant on the the implementation of  'BAL_LOG_MSG_READ' / 'BAL_DSP_TEXT_MSG_READ' and the behaviour of MESSAGE during Unit Tests.

Cheers

Martin

**Comment by FinkeFlo** [comment]
Yes this will fix the issue. 
@AlexandreHT  i think you don't have this issue because there is no translated message in French?

**Comment by martinandrewcavanagh** [comment]
That fix doesn't work for me...
