### ISSUE TITLE
Class to display entries from multiple instances

### ISSUE THREAD

**Issue by cavabap** [ABAP-Logger/ABAP-Logger#81]
Hello ABAP-Logger team,

I find myself often copying a method to display logs from mutliple ABAP Logger instances. To be fair - I had the same problem when using SAP's cf_reca_message_list (mind you - I couldn't find a display method at all there).

Imagine a situation where the programm is processing multipe sales orders and calling a BAPI. The messages from the BAPI may or maynot include the sales order. To handle this, I create an ABAP Logger instance per sales order and use the sales order as the external identification nr (ABAP Logger calls this the desc). This is not a problem for a batch job, unless the program should be executed interactively and the BAL Logs also be displayed to an interactive user - here the display method provided by ABAP-Logger is no longer adequate, as it only displays the messages form one instance (which makes sense).

In my most current example I've created a local class lif_bal_log / lcl_bal_log which creates multiple instances of ABAP Logger and saves the log handle into a member attribute mt_log_handles. 

My suggestion is to create a collection class, which can adds the instances to a table.
Then when the collection display_logs method is called, it could create a table of log handles and excute the coding.

Alternatively the factory class could remember all instances / log handles it creates. But i don't personally like this approach. A factory should problably only be a factory...

Thanks

Martin

`  METHOD lif_bal_log~display_logs.
    DATA: ls_display_profile TYPE bal_s_prof.

    IF mt_log_handles IS INITIAL.
      RETURN.
    ENDIF.

    CALL FUNCTION 'BAL_DSP_PROFILE_STANDARD_GET'
      IMPORTING
        e_s_display_profile = ls_display_profile.

    ls_display_profile-head_size = 125 .
    ls_display_profile-tree_size = 25 .
    IF ls_display_profile-mess_fcat IS NOT INITIAL.
      SORT ls_display_profile-mess_fcat BY no_out ASCENDING col_pos DESCENDING.
    ENDIF.

    CALL FUNCTION 'BAL_DSP_LOG_DISPLAY'
      EXPORTING
        i_s_display_profile  = ls_display_profile
        i_t_log_handle       = mt_log_handles
      EXCEPTIONS
        profile_inconsistent = 1
        internal_error       = 2
        no_data_available    = 3
        no_authority         = 4
        OTHERS               = 5.
    IF sy-subrc <> 0.
      MESSAGE ID sy-msgid TYPE 'S' NUMBER sy-msgno
        WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4 DISPLAY LIKE sy-msgty.
    ENDIF .
  ENDMETHOD.`

**Comment by martinandrewcavanagh** [comment]
I'd be happy to submit a pull request...

**Comment by AlexandreHT** [comment]
Interesting idea. I agree with you on the collection class/interface.

Don't you think it would be more suitable to keep a ```z(if/cl)_abap_logger*``` naming?

Your PR is welcome.

**Comment by martinandrewcavanagh** [comment]
Hi,

yes sure, we should keep it zif_abap_logger naming. That was just my local version...
Now that I've moved to a global class , my current working name is ZIF_LOGGER_COLLECTION + zcl_logger_collection.

Hers the current interace.

`
interface ZIF_LOGGER_COLLECTION
  public .

    METHODS add_logger
      IMPORTING
        i_logger TYPE REF TO zif_logger.
    METHODS display_logs
      IMPORTING
        i_display_profile_head_size TYPE i DEFAULT 125
        i_display_profile_tree_size TYPE i DEFAULT 25
        i_display_profile TYPE bal_s_prof OPTIONAL.
endinterface. 
`

**Comment by AlexandreHT** [comment]
Looks fine.
Could you remove the ```i_``` prefix for parameters in order to be consistent with the existing code base?

**Comment by martinandrewcavanagh** [comment]
Hi,

sure I could...but instead I'm going to challlenge you to look at some of your own coding,

it seems like you've already got two styles - see zif_logger_settings.
Personally I think its nice to have an prefix on the method parameters. Although I dislike prefixing local variables and attributes. Prefixing the method signature means you don't need to prefix a similar attribute / local variable.

Now that I've made my point, yes I'm happy to remove the prefxing.

And here are some examples:

`
  methods set_autosave
    importing
      i_auto_save   type abap_bool
    returning
      value(r_self) type ref to zif_logger_settings.
  methods set_usage_of_secondary_db_conn
    importing
      i_use_2nd_db_connection type flag
    returning
      value(r_self)           type ref to zif_logger_settings.
  methods set_expiry_date
    importing
      i_expiry_date type aldate_del
    returning
      value(r_self) type ref to zif_logger_settings.
 methods set_expiry_in_days
    importing
      i_num_days    type i
    returning
      value(r_self) type ref to zif_logger_settings.

`

**Comment by AlexandreHT** [comment]
True. I'm asking the other maintainers so we take a project decision.

**Comment by AlexandreHT** [comment]
We chose to adhere to Clean Code recommandation regarding prefixing (but we keep non-compliant code for compatibility, for the time being).

Other topic. Isn't ```display_profile_head_size``` and ```display_profile_tree_size``` redundant with ```display_profile``` ?

**Comment by martinandrewcavanagh** [comment]
I think that will make some sense, when I submit my pull request. But I see you know your BAL Log :)

**Comment by anuragguptagithub** [comment]
@martinandrewcavanagh I read your problem description and was wondering, if instead of maintaining member table attribute for log handles, add optional parameter `external_number` in the display method, so that the display method will open the log object for it and display it ?

**Comment by martinandrewcavanagh** [comment]
@anuragguptagithub  why don't you look at the pull request #84?
I'm not maintaining member table attributes. I want the collection to be useful for other (as yet unkown) purposes.

**Comment by AlexandreHT** [comment]
Closed with PR #84
