### ISSUE TITLE
export_to_table do not generate messages from exceptions

### ISSUE THREAD

**Issue by marcelloganzaroli** [ABAP-Logger/ABAP-Logger#83]
Hi All, 

I realized method ZIF_LOGGER~EXPORT_TO_TABLE does not generate a message table from logged exception classes.
The method uses function module 'BAL_LOG_MSG_READ' that cannot read an exception based message. 

**How to replicate:**

1. Create an instance of the logger.
2. Log any other message 
3. Raise any exception with T100
4. log the exception
5. execute export_to_table

I believe something can be done with BAL_LOG_EXCEPTION_READ function but it's quite limited as well.
For my local system and scenario usage, the enhancement bellow was enough, didn't had much time to look further

    DATA: 
          message_handles TYPE bal_t_msgh,
          message         TYPE bal_s_msg,
          bapiret2        TYPE bapiret2,
          exception_log   TYPE bal_s_excr,
          exception_msg   TYPE char255.

    FIELD-SYMBOLS <msg_handle> TYPE balmsghndl.

    message_handles = get_message_handles( ).

    LOOP AT message_handles ASSIGNING <msg_handle>.

      CLEAR bapiret2.
      CALL FUNCTION 'BAL_LOG_MSG_READ'
        EXPORTING
          i_s_msg_handle = <msg_handle>
        IMPORTING
          e_s_msg        = message
        EXCEPTIONS
          OTHERS         = 3.
      IF sy-subrc IS INITIAL.
        MESSAGE ID message-msgid
                TYPE message-msgty
                NUMBER message-msgno
                INTO bapiret2-message
                WITH message-msgv1 message-msgv2 message-msgv3 message-msgv4.

        bapiret2-type       = message-msgty.
        bapiret2-id         = message-msgid.
        bapiret2-number     = message-msgno.
        bapiret2-log_no     = <msg_handle>-log_handle.     "last 2 chars missing!!
        bapiret2-log_msg_no = <msg_handle>-msgnumber.
        bapiret2-message_v1 = message-msgv1.
        bapiret2-message_v2 = message-msgv2.
        bapiret2-message_v3 = message-msgv3.
        bapiret2-message_v4 = message-msgv4.
        bapiret2-system     = sy-sysid.
        APPEND bapiret2 TO rt_bapiret.

      ELSE.

        CALL FUNCTION 'BAL_LOG_EXCEPTION_READ'
          EXPORTING
            i_s_msg_handle = <msg_handle>
            i_langu        = sy-langu
          IMPORTING
            e_s_exc        = exception_log
            e_txt_msg      = exception_msg
          EXCEPTIONS
            log_not_found  = 1
            msg_not_found  = 2
            OTHERS         = 3.
        IF sy-subrc = 0.
          bapiret2-type       = message-msgty.
          bapiret2-log_no     = <msg_handle>-log_handle.
          bapiret2-log_msg_no = <msg_handle>-msgnumber.
          bapiret2-message    = exception_msg.
          APPEND bapiret2 TO rt_bapiret.
        ENDIF.
      ENDIF.
    ENDLOOP.

Thanks :)

**Comment by HuprichT** [comment]
I tested it too and it works for me. Can anyone enlighten me and explain why this should be limited in its function?

**Comment by HuprichT** [comment]
Hi, @mbtools. LGTM, exported Table now has Exception in it. Display Methods are working like expected. 

What I noticed regarding the initial error description from @AlexandreHT: 
The problem is not with the T100, but with the type of exception. CX_DYNAMIC_CHECK is **not** loaded by BAL_LOG_MSG_READ but an exception of type CX_SY_STATIC_CHECK is.

![image](https://github.com/ABAP-Logger/ABAP-Logger/assets/45813255/7281f2d7-67ac-43d6-a441-c3705606e872)

Not sure if this is relevant, the main thing is that it is now running.

**Comment by mbtools** [comment]
it does matter... for implementing a nice unit test 😄
