### ISSUE TITLE
interface for zcl_logger->to enable attributes of customer exception class to be logged

### ISSUE THREAD

**Issue by cavabap** [ABAP-Logger/ABAP-Logger#85]
On the system where I'm using ABAP-Logger there is a customer exception class which carries a message table (bapiret2_t). When unexpected errors in a BAPI or similar occur, an instance of a exception class is thrown and the message table is passed as a parameter. I think other SAP customers would also have a similar exception class.

Now obviously zcl_logger can't be dependant on a customer exception class. But I was thinking a Z-BADI definition would be nice.

Current I've implemented an implizit enhancement (I want ABAP-Logger support without conflicts) at the end of the add method. But I feel a Z-BADI would be better. I don't know if ABAP Git can carry a BADI Definition though.

```
ENHANCEMENT 2 zxxx_enh_logger.
  IF msg_type->type_kind <> cl_abap_typedescr=>typekind_oref.
    RETURN.
  ENDIF.
  DATA customer_error_instance TYPE REF TO zcx_my_abstract_exception_class.
  IF obj_to_log IS INSTANCE OF zcx_my_abstract_exception_class.
    customer_error_instance ?= obj_to_log.
    DATA(messages) = customer_error_instance->get_messages_recursively( ). "customer method!!!
    IF messages IS NOT INITIAL.
      me->add(
        obj_to_log    = messages
        context       = context
        callback_form = callback_form
        callback_prog = callback_prog
        callback_fm   = callback_fm
        type          = type
        importance    = importance ).
    ENDIF.
  ENDIF.
ENDENHANCEMENT.
```

What are your thoughts?

**Comment by AlexandreHT** [comment]
Usually, I log the bapiret2 table after the call and I raise an exception based on the first error message.

This could benefit from the proposition I made in #67 where we could log an object that implements a zif_loggable_object  interface in one call.

**Comment by martinandrewcavanagh** [comment]
Hi, I've read #67 and it seems to be about much more than an interface `zif_loggable_object`.
But I like the idea of `zif_loggable_object` however I feel that there is no need for a new public method in `zif_logger`. I think in the add method, it scould just detect that the instance is `zif_loggable_object' and get the message table and log it. Once #84 is completed, I'd be happy to submit a pull request.

But I don't feel upto rebuilding the internals of zcl_logger just yet as suggested in #67 .

**Comment by martinandrewcavanagh** [comment]
May I make a pull request for an implmentation for zif_loggable_object?

**Comment by AlexandreHT** [comment]
Sure. I agree that it's cleaner to detect zif_loggable_object in the add() method.

**Comment by martinandrewcavanagh** [comment]
I'll try to submit pull request in the next couple of weeks for this...obviously including unit tests

**Comment by cavabap** [comment]
can we close this issue? I think its solved...
