### ISSUE TITLE
Suggestion: new parameter "retention_period" for create_log

### ISSUE THREAD

**Issue by vonglan** [ABAP-Logger/ABAP-Logger#89]
In our systems, I added an optional parameter to create_log. The logic in create_log is then:

```
    if retention_period is not initial.
      lo_log->header-aldate_del = sy-datum + retention_period.
    endif.
```

**Comment by andkopp** [comment]
Hi Edo.
This feature is already implemented. You can pass the expiry date using the settings class (`zcl_logger_settings`, Method `zif_logger_settings~set_expiry_date`) when creating a new log object. Please also see #37 and close the issue if this is what you expect.
Best regards
Andreas

**Comment by vonglan** [comment]
Hi Andreas,
thanks, this is what I have been looking for. 
I will upgrade to the newer version with our next system upgrade.
Best regards,
Edo
