### ISSUE TITLE
Use of squash commits

### ISSUE THREAD

**Issue by pokrakam** [ABAP-Logger/ABAP-Logger#95]
I noticed all my commits were individually merged on my last PR. 

No problem if this is intentional, but if not then I would suggest using [squash commits](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges) in most cases. It keeps the commit history cleaner as all the commits of a PR are rolled up into a single commit and we won't have all the minor work in progress commits in the history.

**Comment by AlexandreHT** [comment]
Thanks for the suggestion. I'll keep this in mind for the next PR to merge.
