### ISSUE TITLE
Inconsistent pretty print

### ISSUE THREAD

**Issue by mbtools** [ABAP-Logger/ABAP-Logger#96]
Some classes use all lower case while others are formatted with upper case keywords. It would be helpful for maintainers to settle on one setting (and then set abaplint rule keyword_case accordingly).

**Comment by AlexandreHT** [comment]
Agreed. As a maintainer, I would like to reach a consensus among contributors before settling on one rule. Could everyone state its preferred option ?
(Mine is all lowercase)

**Comment by mbtools** [comment]
In general, I use keyword upper case. But any setting will do since I use an exit to auto pretty print the code:
https://gist.github.com/mbtools/71aa345a8ccb8f375568f9f337569154

**Comment by pokrakam** [comment]
While I would personally prefer lowercase, a large majority of the ABAP world uses keyword upper so I follow that trend.
Also see the Style Guides commentary on the topic. 
https://github.com/SAP/styleguides/blob/main/clean-abap/sub-sections/UpperVsLowerCase.md

In general I would recommend keyword upper for OSS projects as that will be 'normal' to the majority. If a customer downloads something and makes a small edit for whatever local reasons and out of habit presses shift-f1 then it becomes difficult to pick up future deltas. 

Also see same discussion on [ABAP2XLSX](https://github.com/sapmentors/abap2xlsx/issues/780)

**Comment by AlexandreHT** [comment]
Thanks @mbtools for your exit. It's a game changer. I'll go for keyword uppercase for the repo (since the formatting is now automatic).

**Comment by andkopp** [comment]
I also prefer uppercase keywords, probably because I am used to it.
Automatic pretty print before committing would be really nice.
